server:
  port: 9000

  cloud:
    config:
      server:
        git:
          uri: git@github.com:socketing-refactoring/config-repository.git
          ignoreLocalSshSettings: true
          privateKey: |
            ${SSH KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  config: classpath:logback-spring.xml

user:
  username:
    username
  password:
    password
  role:
    role