server:
  port: 9000

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:socketing-refactoring/config-repository.git
          ignoreLocalSshSettings: true
          privateKey: |
            ${SSH KEY}

management:
  endpoints:
    web:
      exposure:
        include: "health"

logging:
  level:
    root: INFO

user:
  username:
    username
  password:
    password
  role:
    role